### ISSUE TITLE
Testing Samples fails on Radeon HD 5850

### ISSUE THREAD

**Issue by OvermindDL1** [ronsaldo/abstract-gpu#1]
Testing Samples, any of them, just reports back:

``` text
Failed to get AGPU platform
```

It appears there is no fallback renderer defined.
System:  Ubuntu 16.04
GPU:  AMD/ATI Cypress PRO [Radeon HD 5850]
As this is not that old then it should be able to support some type of fallback for this library to be able to work.  Only supporting systems that are ~1-2 years old is significantly limiting for distributing finished programs.

**Comment by ronsaldo** [comment]
The abstract GPU is being designed to use newer low level graphics. There was an OpenGL renderer that was being used for prototyping things. It should be still possible to keep maintaining this renderer, but the biggest problem with it is the lack of separate sampler state and texture in OpenGL. The current plan is on removing the OpenGL backend, which has several problems due to the bad design of OpenGL (Current context is a variable, framebuffer object state cannot be shared between different contexts).

As for AMD graphics cards, its been tested on a HD 7770 and a HD 8650M on Windows. For Linux, Vulkan drivers are required. The HD 7000 series was released in 2012. That is far more than 2 years old hardware.

**Comment by OvermindDL1** [comment]
Was looking for an abstraction around Vulkan and OpenGL, Vulkan is significantly better designed but I have no hardware that supports it...

**Comment by ronsaldo** [comment]
Vulkan is still very green. The glslangValidator shader compiler is not implementing the extension for translating to Vulkan last time I checked, which adds the separate sampler state. For this reason, I had to edit manually the intermediate representation for getting working the sample 3 that uses textures. The intel anvil driver is also incomplete, and with this samples I even triggered a bug that was a clear violation of the Vulkan spec on purpose. Currently, I would not recommend to use Vulkan, until the tools and specially the drivers get stabilized. Anyway, I think that could get the OpenGL backend back to work. However, it is quite buggy. Last time I checked it seemed to have a memory leak on windows.

**Comment by OvermindDL1** [comment]
Hmm, interesting, is the memory leak in the driver or the local code?

**Comment by ronsaldo** [comment]
The memory leak was because I was trying to simulate the multiples command queues of Direct3D 12 or Vulkan by using multiples OpenGL context. I do not know if this was because of a driver issue or because I was making a mistake when simulating a shared FBO.

Anyway. I removed the support for the multiples command queues, so now this should be serializing everything in a single OpenGL context. Can you try with the latest version of the samples?

**Comment by OvermindDL1** [comment]
It appears to work, ran through valgrind and only CPU memory leak was in my local SDL build, unsure of any GPU leaks but it looks solid.  Looks good.

By removing multiple command queues do you mean you cannot even build them up in parallel threads then submit them in a single thread once built now, or...?
