### ISSUE TITLE
Bypass dispatcher/static link

### ISSUE THREAD

**Issue by boberfly** [ronsaldo/abstract-gpu#2]
Hi Ronsaldo,

Great project! Very cool. I like the design abstraction of this library as it is forward-thinking in regards to the modern APIs, but also has the GL fallback that 'emulates' command buffers so that you could do fake threaded command building if you wanted and delegate it to the single GL context thread (at least this is what I think that is happening while browsing the code). You did mention you wanted to drop the GL back-end, I hope you don't but I guess one could fork the project anyways.

I was wondering, would you be happy if there was a compile-time option to just bypass the dispatcher and wrap a single API of choice, so that you don't want to pay for the dispatcher/ICD pointer overhead? I'm thinking for the cases where someone wanted to just statically link AGPU into a game engine for a target platform that would only support one API anyways. Perhaps the overhead concerns aren't too bad these days, you can correct me on this.

Cheers

**Comment by ronsaldo** [comment]
Hi Boberfly,

I am not going to be dropping the OpenGL backend anytime soon. Unfortunately, I have some demand for it because of OS X (and Metal gives a nil device in 32 bits applications). Currently the only backend that it is completely maintaned is the Vulkan based backend, because is the one that I am using for building Woden 2 ( https://www.youtube.com/watch?v=fnPv7jtVY8U ). Since the Squeak VM that we are using is 32 bits only for now, and in the community OS X is used a lot, then I have to keep the OpenGL fallback.

As for avoiding the dispatch/ICD overhead, it is enough to just link the executable/game engine directly with the ICD .dll/static library. The ICD keeps the exact same interface as the dispatcher. As for the overhead itself of function calls, it does not matte because most of the communication with the GPU is done by just writing into a buffer in GPU memory. 

It also seems that I should start adding more examples.

**Comment by boberfly** [comment]
Thanks for the reply Ronsaldo. More examples are good, although I have a decent enough background on low-level graphics APIs to understand what's going on.

I was thinking the same in terms of function calls, I think it's more an issue with platforms with higher API calls like perhaps GL, but in practice it might not be too bad. I can take a look at porting to ES 3.1 also, as my targets are basically VR-spec including mobile VR which would most likely be Vulkan anyways, but ES 3.1 is a neat fallback (perhaps WebGL2 as well). This is the overhead stuff I was thinking of: http://aras-p.info/blog/2011/02/01/the-virtual-and-no-virtual/
